OrdererOrgs:
- CA:
    Country: TR
    Locality: TURKEY
    OrganizationalUnit: ""
    PostalCode: ""
    Province: Ankara
    StreetAddress: ""
  Domain: orderer
  Name: Orderer
  Specs:
  - SANS:
    - localhost
  Template:
    Count: 1
    Hostname: orderer{{.Index}}
PeerOrgs:
- CA:
    Country: TR
    Hostname: ca
    Locality: TURKEY
    OrganizationalUnit: ""
    PostalCode: ""
    Province: Ankara
    StreetAddress: ""
  Domain: customer
  EnableNodeOUs: true
  Name: Customer
  Template:
    Count: 2
    SANS:
    - localhost
  Users:
    Count: 1
- CA:
    Country: TR
    Hostname: ca
    Locality: TURKEY
    OrganizationalUnit: ""
    PostalCode: ""
    Province: Ankara
    StreetAddress: ""
  Domain: serviceProvider
  EnableNodeOUs: true
  Name: ServiceProvider
  Template:
    Count: 2
    SANS:
    - localhost
  Users:
    Count: 1
- CA:
    Country: TR
    Hostname: ca
    Locality: TURKEY
    OrganizationalUnit: ""
    PostalCode: ""
    Province: Ankara
    StreetAddress: ""
  Domain: insuranceCompany
  EnableNodeOUs: true
  Name: InsuranceCompany
  Template:
    Count: 2
    SANS:
    - localhost
  Users:
    Count: 1
- CA:
    Country: TR
    Hostname: ca
    Locality: TURKEY
    OrganizationalUnit: ""
    PostalCode: ""
    Province: Ankara
    StreetAddress: ""
  Domain: legalAuthority
  EnableNodeOUs: true
  Name: legalAuthority
  Template:
    Count: 3
    SANS:
    - localhost
  Users:
    Count: 1
